"""empty message

Revision ID: 43e3712b519b
Revises: 
Create Date: 2020-06-26 15:47:13.491439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e3712b519b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Recruiter',
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('recruiter_name', sa.String(length=32), nullable=False),
    sa.Column('recruiter_age', sa.Integer(), nullable=True),
    sa.Column('recruiter_gender', sa.Enum('MAN', 'WOMAN'), nullable=True),
    sa.Column('recruiter_mobile', sa.String(length=11), nullable=False),
    sa.Column('recruiter_email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('recruiter_id')
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_psw', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('department',
    sa.Column('depart_id', sa.Integer(), nullable=False),
    sa.Column('depart_name', sa.String(length=32), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('depart_id')
    )
    op.create_table('superadmin',
    sa.Column('superadmin_id', sa.Integer(), nullable=False),
    sa.Column('superadmin_psw', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('superadmin_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('user_age', sa.Integer(), nullable=True),
    sa.Column('user_gender', sa.Enum('MAN', 'WOMAN'), nullable=True),
    sa.Column('depart_id', sa.Integer(), nullable=True),
    sa.Column('user_mobile', sa.String(length=11), nullable=False),
    sa.Column('user_email', sa.String(length=60), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['depart_id'], ['department.depart_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rewardspunishment',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=True),
    sa.Column('punishment', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rewardspunishment')
    op.drop_table('user')
    op.drop_table('superadmin')
    op.drop_table('department')
    op.drop_table('admin')
    op.drop_table('Recruiter')
    # ### end Alembic commands ###
